<?php
/**
 * @var \Magento\Sales\Block\Order\Email\Items\DefaultItems $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Nfourteen\AggregateProduct\ViewModel\Sales\Order\Items\Renderer $viewModel
 */
$_item = $block->getItem();
$viewModel = $block->getViewModel();
?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <p class="product-name"><?= $escaper->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= $escaper->escapeHtml(__('SKU')) ?>: <?= $escaper->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option): ?>
                    <dt><strong><em><?= $escaper->escapeHtml($option['label']) ?></em></strong></dt>
                    <dd>
                        <?= /* @noEscape */ nl2br($escaper->escapeHtml($option['value'])) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock): ?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $escaper->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= (float) $_item->getQty() ?></td>
</tr>
<?php
$children = $_item->getOrderItem()->getChildrenItems();
if ($children && count($children) > 0): ?>
    <tr>
        <td class="item-info" colspan="2">
            <p><strong><?= $escaper->escapeHtml(__('Includes')) ?></strong></p>
        </td>
    </tr>
    <?php foreach ($children as $child): ?>
        <tr>
            <td class="item-info">
                <p><?= $escaper->escapeHtml($viewModel->getValueHtml($child)) ?></p>
            </td>
            <td class="item-qty">&nbsp;</td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>
